run:
  timeout: 5m
  go: '1.24'

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - errcheck
    - gosimple
    - staticcheck
    - unused
    - typecheck
    - gocritic
    - gosec
    - cyclop
    - dupl
    - funlen
    - gocognit
    - goconst
    - revive

linters-settings:
  funlen:
    lines: 100
    statements: 50
  cyclop:
    max-complexity: 15
  gocognit:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - dupl
        - goconst